### ISSUE TITLE
[ERROR] Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by angelhdzmultimedia** [facing-dev/vue-facing-decorator#1]
### Context
This package was suggested in the vue-class-component repository as "working". So I decided to try it.
Installed it from npm. Didn't work. So copied all the files directly into my stackblitz.com project.

Got this error:

```
ref.ts:14 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at build (ref.ts:14:9)
    at Component (component.ts:20:3)
    at __decorateClass (App.vue:7:57)
    at App.vue:8:1
```

Script:

```ts
import HelloWorld from './components/HelloWorld.vue';
import { Component, Ref, Base } from './vue-decorator';

@Component
export default class App extends Base {
  mounted() {
    //vue lifecycle
    console.log(this.ref, this.prop, this.supProp, this.getter, this.supGetter);
  }
}
```

So logically, tried to match my project's tsconfig.json with this package's one. No success.

Then tried to add options to the component decorator:

```ts
@Component({
  components: {
    HelloWorld,
  },
})
```

Got a different issue:

```
utils.ts:19 Uncaught TypeError: Cannot read properties of undefined (reading 'Symbol(vue-facing-decorator-slot)')
    at getSlot (utils.ts:19:12)
    at obtainSlot (utils.ts:23:18)
    at build (computed.ts:6:18)
    at Component (component.ts:18:3)
    at App.vue:7:2
```

**Comment by ruojianll** [comment]
Thanks for your reporting. First version 1.0.1 has released now. Bug fixed.

**Comment by ruojianll** [comment]
@angelhdzmultimedia Use `npm install -S vue-facing-decorator`

**Comment by angelhdzmultimedia** [comment]
> vue-facing-decorator

Works now, thanks. We'll keep testing the following days and help you report any further issue. I have faith in this projects, as is only 1 package with everything needed for Vue Class-based Components.

![image](https://user-images.githubusercontent.com/10191085/171997542-fae18e4a-26fa-4750-a879-cb28b1a9c2f2.png)

**Comment by ruojianll** [comment]
@angelhdzmultimedia Thanks for your help. Many people will need these features.
