### ISSUE TITLE
toNative with PhpStorm

### ISSUE THREAD

**Issue by julienbrunet21** [facing-dev/vue-facing-decorator#103]
Vue may remove supporting for old class component. I suggest using `toNative` in every recent projects, it could provide best compatibility.

_Originally posted by @ruojianll in https://github.com/facing-dev/vue-facing-decorator/issues/65#issuecomment-1862185914_

**Comment by julienbrunet21** [comment]
Hello,
Thanks for the work provided with vue-facing-decorator.

I'm facing the same issue reported here : https://github.com/facing-dev/vue-facing-decorator/issues/65

As said by @ruojianll above, I'm trying to use 'toNative' to solve my issue.
With 'toNative', HMR works well but I have a problem with PhpStorm that is not recognizing methods and imported components anymore.

Here is an example : 
```
<script lang="ts">
import { Component, toNative, Vue } from 'vue-facing-decorator';
import AppBtn from '@/shared/component/btn/AppBtn.vue';

@Component({ AppBtn })
class HelloWorld extends Vue {
  get label(): string {
    return 'HelloWorld';
  }
}
export default toNative(HelloWorld);
</script>

<template>
  <AppBtn></AppBtn>
  {{ label }}
</template>

<style scoped></style>
```

PhpStorm displays following errors :
```
Vue: Object literal may only specify known properties, and 'AppBtn' does not exist in type 'ComponentConsOption'.
Unresolved variable or type label
Component AppBtn is not imported
```
![image](https://github.com/facing-dev/vue-facing-decorator/assets/26904606/95a098db-4c3a-4698-9b55-93886b77c546)

Can someone help ?

**Comment by ruojianll** [comment]
Sorry, we can't provide any support for IDEs at the moment.

**Comment by julienbrunet21** [comment]
Hello,

Thanks for your reply.

I'll open an issue on the JetBrain's tracker and I'll keep this feed updated for those who might face the same issue.

**Comment by julienbrunet21** [comment]
Hello, just got an answer from the JetBrain's team saying that there is not ETA for implementing the support of toNative in PhpStorm at the moment...
