### ISSUE TITLE
无法在 uni-app 的 h5 模式正常运行

### ISSUE THREAD

**Issue by pecasha** [facing-dev/vue-facing-decorator#108]
使用 vue-facing-decorator 的项目可以在 uni-app 的小程序模式正常运行，但是如果运行到 h5 模式，会出现警告：`Component provided template option but runtime compilation is not supported in this build of Vue. Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js".`
页面不能正常显示，不知道是不是因为 uni-app 的 h5 模式默认强制 `runtimeCompiler` 固定为 false 导致的。

并且 vite 配置 vue 别名指向 `vue/dist/vue.esm-bundler.js` 也无效，会导致其它错误

**Comment by ruojianll** [comment]
根据你的错误提示，有两个解决方案1、Vue的模版编译需要在编译时运行而不是运行时运行。2、使用vue带编译器的版本在运行时进行模版编译。
这不是v-f-d的issue。
