### ISSUE TITLE
Unexpected context `this` when property has a function value 

### ISSUE THREAD

**Issue by ruojianll** [facing-dev/vue-facing-decorator#11]
```ts
@Component 
class C extends Vue{
  p=function(){}//`this` context is not same to a method
}
```

**Comment by carlossantos74** [comment]
Perhaps the issue you are experiencing is a role scope/context issue. Maybe this can help you. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
