### ISSUE TITLE
Can't override render function with a template block

### ISSUE THREAD

**Issue by Logima** [facing-dev/vue-facing-decorator#116]
Overriding render function with a template block doesn't seem to work.

For example:

Sup.vue:
```vue
<script lang="ts">
import { h } from 'vue'
import { Base, Component, toNative } from 'vue-facing-decorator'

@Component
export class Sup extends Base {
    render() {
        return h('div', 'Sup')
    }
}
</script>
```

Comp.vue:
```vue
<template>
    <div>Comp</div>
</template>

<script lang="ts">
import { Sup } from './Sup.vue'
import { Component } from 'vue-facing-decorator'

@Component
export class Comp extends Sup {}
</script>
```

Using Comp results `<div>Sup</div>` to be rendered.

This used to work with vue-class-component. If Comp implements render function or defines template as `@Component({ template: '<div>Comp</div>' })`, output is working as intended.

**Comment by ruojianll** [comment]
Try https://facing-dev.github.io/vue-facing-decorator/#/en/class-component/component/component?id=render
