### ISSUE TITLE
Upgrading `vue-tsc` from 2.0.29 to 2.1.x results in hundreds of TypeScript errors

### ISSUE THREAD

**Issue by basil** [facing-dev/vue-facing-decorator#128]
Upgrading `vue-tsc` and `@vue/language-core` from 2.0.29 to 2.1.0 (and nothing else) results in 283 new TypeScript errors for me. To reproduce, check out https://github.com/neanes/neanes/pull/933 and run `npm install && npm run build`. The default branch builds correctly. This issue was originally reported at https://github.com/vuejs/language-tools/issues/4748, where @davidmatter wrote that

> https://github.com/facing-dev/vue-facing-decorator seems to be the problem here

**Comment by ruojianll** [comment]
I cloned `git@github.com:basil/neanes.git`, run 
1. `git checkout vue-tsc-2.1.0`
2. `npm install`
3. `npm run dev`
No error found in electron app.

**Comment by juanparati** [comment]
@ruojianll: I cannot reproduce this issue vue-tsc 2.1.0, however I face this issue with 2.1.2.

It seems that vue-tsc 2.1.2 cannot infer the components types.

Please see: https://github.com/vuejs/language-tools/issues/4747

@basil : Are you sure that you didn't installed vue-tsc 2.1.2?, can you check you package-lock.json?

**Comment by ruojianll** [comment]
It's possible, vite-plugin-vue also removed decorator support in .vue file.

https://github.com/vitejs/vite-plugin-vue/issues/430

Use some temporary resolutions such as ts `any` at the moment.

**Comment by basil** [comment]
> @basil : Are you sure that you didn't installed vue-tsc 2.1.2?, can you check you package-lock.json?

Checking the `package-lock.json` file from https://github.com/neanes/neanes/pull/933/files, I am using 2.1.0.

**Comment by basil** [comment]
Hi @ruojianll, I saw that the related PR https://github.com/vuejs/language-tools/pull/4763 was released in 2.1.4. As you can see from the CI build for https://github.com/neanes/neanes/pull/936, this does not resolve the issue and I still get 283 new TypeScript errors with `vue-tsc` 2.1.4.

**Comment by MeesterDev** [comment]
I cannot reproduce this with vue-tsc 2.1.0, but can with 2.1.2.

Node v20.17.0
npm 10.8.1

**Comment by basil** [comment]
Fixed in https://github.com/vuejs/language-tools/releases/tag/v2.1.8
