### ISSUE TITLE
Class extends value #<Object> is not a constructor or null

### ISSUE THREAD

**Issue by markus-petelinc** [facing-dev/vue-facing-decorator#133]
When extends components, the following problem occurs:
**Class extends value #<Object> is not a constructor or null**

Both classes are in seperated .vue files and contain template and css.

With Vue2 Class Decorators it was possible to extends .vue files with the template directly and the template and css was taken over from the extended class.

Does anyone have a solution for this problem without splitting .vue files into .ts, .html, .css ....

```typescript
<script lang="ts">
import {Vue, Component, Inject} from 'vue-facing-decorator';

@Component
export default class Main extends Vue {

}
</script>

<template>
    <main class="responsive">
        <slot></slot>
    </main>
</template>

<style scoped>

</style>
``` 

```typescript
<script lang="ts">
import {Vue, Component, Inject} from 'vue-facing-decorator';
import Main from "@/components/Main.vue";

@Component
export default class Main2 extends Main {

}
</script>

```

**Comment by mattkenefick** [comment]
I've been exploring this too. I think it's because you're exporting the default.

That was common in Vue2 but now you have to export the class and component separately if you want to extend multiple, so like this.


```
// Main.ts
import { Component, toNative } from 'vue-facing-decorator';

@Component
export class Main extends Vue {

}
```


```
// Main2.ts
import { Main } from './Main';
import { Component, toNative } from 'vue-facing-decorator';

@Component
export class Main2 extends Main {

}
```
