### ISSUE TITLE
What is the equivilant of Model decorator

### ISSUE THREAD

**Issue by rootux** [facing-dev/vue-facing-decorator#15]
What is the equivalent of @Model Decorator -  
https://github.com/kaorun343/vue-property-decorator#-modelevent-string-options-propoptions--constructor--constructor---decorator

**Comment by ruojianll** [comment]
See https://facing-dev.github.io/vue-facing-decorator/#/en/class-component/v-model/v-model

**Comment by rootux** [comment]
Exactly what I needed :pray: 
so `@Model('something')` has changed to `@VModel({name: 'something'})`
