### ISSUE TITLE
Unused dead code comments

### ISSUE THREAD

**Issue by rootux** [facing-dev/vue-facing-decorator#16]
Hey.

We have all this commented out code.
Why is that?
Is it needed?

// const slot = getSlot(cons.prototype)!
        // Object.defineProperty(cons, '__vccOpts', {
        //     value: slot.cachedVueComponent
        // })
        // console.log('kkkk', '__vccOpts' in cons, cons)
        // return cons

https://github.com/facing-dev/vue-facing-decorator/blob/295cff94576768c53bee880a4dcf884a95ec79b5/src/component.ts#L126/

**Comment by ruojianll** [comment]
A standard VUE options component is a javascript plain object `{}`, not a class constructor. `__vccOpts` is used in internal VUE implementation to access the options component from a class constructor. So `vue-class-component` could provide a native class way to write  a class component and which could be used as VUE component everywhere. But `__vccOpts` is not in document. It's is an unsafe feature and may be deprecated in the future. So I make two decorators to define component (`Component`, `ComponentBase`). `Component` receives a class constructor and returns a plain VUE option component, and `ComponentBase` returns the class constructor which it received for inheritance.
