### ISSUE TITLE
console.log in code

### ISSUE THREAD

**Issue by ecSpl01t** [facing-dev/vue-facing-decorator#17]
Hi there!
Thank you for your job!
I'm just wondering about console.log (for ex: https://github.com/facing-dev/vue-facing-decorator/blob/7567cb0bf961ababcb36391840b5f1e6c2da52a5/src/option/ref.ts#L22)
It's just mistake that you put it `console.log` in published lib ?

**Comment by ruojianll** [comment]
Sorry for that, I will check and clear the package.

**Comment by ruojianll** [comment]
v2.1.5 released
