### ISSUE TITLE
Support multiple @Watch decorators per function

### ISSUE THREAD

**Issue by maxwrlr** [facing-dev/vue-facing-decorator#18]
Hey there,
[vue-property-decorator supports multiple @Watch decorators per class method](https://github.com/kaorun343/vue-property-decorator#Watch).
It would be amazing if this library would have it as well.

**Comment by maxwrlr** [comment]
Thanks, it is now working!

Side note: I have looked at your according commit and the actual test case should be something like:
```typescript
@Watch('defaultWatchKey')
@Watch('fullWatchKey')
multiWatcher() {
  // ...
}

**Comment by ruojianll** [comment]
@maxwrlr That's a case in test, I will add it.
