### ISSUE TITLE
[SUGGESTION] Rename Library

### ISSUE THREAD

**Issue by angelhdzmultimedia** [facing-dev/vue-facing-decorator#19]
I suggest renaming the library to a clear name that says what it is about.

vue-oop is already taken.

So maybe:

1.  vue-oop-component
2.  vue-component-oop
3.  vue-oop-decorator
4.  voop
5.  vue-decore
6.  vue-oop-decore
7.  vue-oop-api
8.  vue-class-api

 
 Also, I might get involved with this repo if you are really commited to mantain it and you aren't going to deprecate it in the near future. I can help with english and spanish translations. I can even help with designing the logo and other UI.
 I can then spend few months reading all the source code to familiarize with it, so I can even help in the maintance of the code.
 
 This has the potential to be a replacement to the now deprecated official vue-class-component package.
 
 I really love OOP's syntax but also know its benefits so I'm trying to advocate about this.
 Instead of learning OOP now they use a lot of mental gymnastics (hooks) not knowing how many libraries they use are made with classes and with an OOP based API that they instantiate (by calling functions) and call its methods and properties.
 
 You can contact me via Telegram or Discord.

**Comment by ruojianll** [comment]
I won't deprecate this package in the near future. In fact this package is almost finished on stable vue options api. Bug will be fixed and more feature will be added if community desired.
For new name, I think about it.

**Comment by ruojianll** [comment]
@angelhdzmultimedia Discord server https://discord.gg/4exxtFgkcz

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia Discord server https://discord.gg/4exxtFgkcz

Discord link won't open, sorry to bother you. 😪
