### ISSUE TITLE
[BUG?] No Prop Intellisense

### ISSUE THREAD

**Issue by angelhdzmultimedia** [facing-dev/vue-facing-decorator#22]
Not getting prop intellisense:

![image](https://user-images.githubusercontent.com/10191085/185739095-f9ff5f61-ddf8-42ee-b2a6-763dd179afdc.png)

Tried with normal `<script setup>` without using vue-facing-decorator and I then get intellisense:

![image](https://user-images.githubusercontent.com/10191085/185739142-abec3f7b-3253-4fe3-a180-03de6e790cc2.png)

components/HelloWorld.vue with vue-facing-decorator:
```vue
<script  lang="ts">
import {
  Vue,
  Component,
  Prop,
  Emit,
  
} from 'vue-facing-decorator'
@Component
export default class App extends Vue {
@Prop({})
 public name?: string
}
 
</script>

<template>
  Name: {{name}}
</template>

<style scoped>

</style>

```
components/HelloWorld.vue without vue-facing-decorator:
```vue
<script setup lang="ts">
const {name} = defineProps(['name'])
</script>

<template>
  {{name}}
</template>

<style scoped>

</style>
```

Am I missing something? Thank you.

**Comment by ruojianll** [comment]
So far, I don't known the details of SFC intellisense. Maybe vscode plugin analyze vue composition api to get these info or with other ways. In opposed, TSX's component type intellisense is well documented. So SFC intellisense is not be considered while I creating this repo. I will focus on it, but it won't be supported in recent days probably.

**Comment by angelhdzmultimedia** [comment]
Wow quick reply. 🤯

Yes I understand and it makes sense. I will try TSX out. Thanks for replying.

**Comment by Lordmau5** [comment]
Hey, I just stumbled upon this repository after finding some other good ones, like unplugin-auto-import and unplugin-vue-components

I did encounter the props issue as well, a bit of a bummer, but nothing that makes developing with it impossible.

Additionally, it also seems to extend to emits as well...

I know it's been over a year since this was last discussed, but is this still something that is being considered? :)

**Comment by ruojianll** [comment]
@Lordmau5 So far, we didn't have enough time to improve IDE develop experience. I someone could point out how to support it, then I'd like to implement it. I hope more people could work in this repo for making it better.
