### ISSUE TITLE
TypeError DecorateConstructor 

### ISSUE THREAD

**Issue by DanMiMe** [facing-dev/vue-facing-decorator#24]
Hello,

I am trying to migrate a big vue2 to vue3 project using this package, but getting a Type Error.
TypeError
    at DecorateConstructor (Reflect.js:544:1)
    at Reflect.decorate (Reflect.js:130:1)
    at __decorate (Home.vue?20b9:8:40)
    at ../node_modules/ts-loader/index.js??clonedRuleSet-1!../node_modules/vue-loader/dist/index.js??ruleSet[1].rules[7].use[0]!./src/Home.vue?vue&type=script&lang=ts (Home.vue?b127:11:26)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/Home.vue?vue&type=script&lang=ts (Home.vue:27:16)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/Home.vue (Home.vue?bf7e:209:2)
    at Function.__webpack_require__ (bootstrap:19:1)

Home.vue:
see attachment.

Dependencies:
frontend:
"vue": "^3.2.37",
"vue-router": "^4.1.4",
"vuesax": "^3.12.2",
"vuetify": "^3.0.0-beta.8",
"vuex": "^4.0.2"
"vue-class-component": "^8.0.0-rc.1",
"vue-facing-decorator": "^2.1.8",

building:
"css-loader": "^6.7.1",
"ts-loader": "^9.3.1",
"fork-ts-checker-webpack-plugin": "^7.2.13",
"vue-loader": "^16.0.0",
"vue-style-loader": "^4.1.3",
"vue-template-compiler": "^2.7.8",
"webpack": "^5.74.0",

Typescript 4.7.3
Node: v16.15.0

Removing the line: throw new TypeError(); in Reflect.js then it works...
`function DecorateConstructor(decorators, target) {
            for (var i = decorators.length - 1; i >= 0; --i) {
                var decorator = decorators[i];
                var decorated = decorator(target);
                if (!IsUndefined(decorated) && !IsNull(decorated)) {
                    if (!IsConstructor(decorated))
                        throw new TypeError();
                    target = decorated;
                }
            }
            return target;
        }`
[Home.vue.txt](https://github.com/facing-dev/vue-facing-decorator/files/9402958/Home.vue.txt)

**Comment by DanMiMe** [comment]
I have removed vue-class-component, but no changes.
Reflect.js is in package "reflect-metadata", which is a dependency of "serialazy" (used for TS Object serialization). 

Stack trace has this line:
../node_modules/ts-loader/index.js??clonedRuleSet-1!../node_modules/vue-loader/dist/index.js??ruleSet[1].rules[7].use[0]!./src/App.vue?vue&type=script&lang=ts (App.vue?5b83:13)
Can be a problem with ts-loader, or vue-loader ?

**Comment by ruojianll** [comment]
I will release a reflect-metadata compatible version after a while.

**Comment by ruojianll** [comment]
V2.1.10 release
https://facing-dev.github.io/vue-facing-decorator/#/en/compatibility/reflect-metadata/reflect-metadata

**Comment by DanMiMe** [comment]
IT WORKSSS !! Many thanks 👍
