### ISSUE TITLE
No SFC: CSS and html

### ISSUE THREAD

**Issue by viT-1** [facing-dev/vue-facing-decorator#28]
How can I use [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)? I am using [iam-css methodology](https://vit--1-github-io.translate.goog/iAMcss/?_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=ru&_x_tr_pto=wapp).
How can I import template as a simple String in js-file?

**Comment by ruojianll** [comment]
This is just a translator from class component to vue options component. I think you should ask this question to vue.

If you want import a template string rom a js, try this https://github.com/facing-dev/vue-facing-decorator/issues/4
