### ISSUE TITLE
An error occurred when exporting interface.

### ISSUE THREAD

**Issue by jinyongp** [facing-dev/vue-facing-decorator#32]
```vue
<!-- ParentComponent -->
<template>
  <Test state="World" />
</template>

<script lang="ts">
import Test from './components/Test.vue'

export default {
  components: {
    Test,
  },
}
</script>
```

```vue
<!-- ChildComponent -->
<template>
  <div>Hello, {{ name }}</div>
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-facing-decorator'

export interface TestOption { // make error
  value: any
}

@Component({})
export default class TestComponent extends Vue {
  @Prop({ default: '' })
  readonly name!: string
}
</script>
```

Exception raised: `Uncaught TypeError: Class constructor TestComponent cannot be invoked without 'new`

This error did not occur in `vue-property-decorator`. I want to export interface in script as before.

**Comment by ruojianll** [comment]
No error occurred in my test project. But any exported type in `.vue` file will lost.

**Comment by jinyongp** [comment]
You can reproduce this error in a project created by vite(vue-ts). I've just checked.

**Comment by ruojianll** [comment]
Vite does not support decorators nowadays. If you found a solution to support decorators in vite, please share it. Maybe some vite plugins could do that.

If decorators work, it will be fine.

**Comment by ruojianll** [comment]
Do not mix `export default` in to your component declaration.
try
```
@Component({})
class TestComponent extends Vue {
  @Prop({ default: '' })
  readonly name!: string
}

export default TestComponent
```

**Comment by jinyongp** [comment]
Thank you for your solution. You saved so much time for me. But, I don't understand why this error occurs. Would you mind explaining why?

**Comment by ruojianll** [comment]
I'm not sure, but in community, `@Decorator` is before or after of `export` is in discussing and decorator proposal is not stable(Stage 3). So vue compiler may have some temporary unexpected behaviors.

```
@Deco
export class A{}

export @Deco class B{}   // They like this syntax more.
```
