### ISSUE TITLE
Error on Vue Component import using JEST + VFD

### ISSUE THREAD

**Issue by Icepick** [facing-dev/vue-facing-decorator#33]
Vue Component
```typescript
<template>
  <div class="area" :class="{ 'area--indented': hasIndent}">
    <slot />
  </div>
</template>

<script lang="ts">
import { Vue, Prop, Component } from 'vue-facing-decorator';

@Component
class Area extends Vue {
  @Prop() hasIndent = false;
}
export default Area;
```

Jest Test
```typescript
import { mount } from '@vue/test-utils';
import Area from './Area.vue';

describe('Area Component', () => {
  it('should render a non indented area', () => {
    const wrapper = mount(Area, {
      slots: {
        default: ['<p>lorem ipsum</p>'],
      },
    });
    expect(wrapper.html()).toBe('<div class="area"><p>lorem ipsum</p></div>');
  });
});
```

We switched from vue-class-component to vue-facing-decorator, which worked well for the components but not for the tests, using JEST. We get the following error, which we did not experienced before. Setup is Vue3 + Vite + Typescript. Do you know why this is the case? Any help is appreciated.

Error
```error
Class constructors cannot be invoked without 'new'
TypeError: Class constructors cannot be invoked without 'new'
```

```
"vue": "^3.2.29",
"vue-facing-decorator": "^2.1.12",
"vite": "^3.2.5",
"jest": "^29.0.0",
"jest-environment-jsdom": "29.0.0",
"@vue/vue3-jest": "^29.2.2",
"@vue/test-utils": "^2.2.7",
```

**Comment by ruojianll** [comment]
It's seem to a class not decorated by a `@Component` decorator or the decorator doesn't work passed to vue. Vue couldn't use a class(constructor) as a component directly.

**Comment by Tahtawy** [comment]
Hi @ruojianll 
I have the same problem, here is my repo: https://github.com/Tahtawy/vue-facing-decorator-test

**Comment by ruojianll** [comment]
Jest seems to call class super in an incorrect way. It calls super as a function. So components inherit `Vue` from v-f-d cause the error.
```
TypeError: Class constructors cannot be invoked without 'new'
      20 |   constructor(a: any, b: any) {
      21 |     console.log('c3', a, b)
    > 22 |     super(a, b)
         |     ^
      23 |     console.log('c4')
      24 |   }
```

**Comment by Icepick** [comment]
Thank you @Tahtawy for providing an example repo and @ruojianll for your investigation.
We were able to fix the problem by migrating Jest to Vitest.

**Comment by cah-keyan-hardman** [comment]
Did anyone find a solution to this? I'd prefer to continue using jest.

**Comment by cah-keyan-hardman** [comment]
I would be interested in helping fix if you could point me in the right direction.

**Comment by ruojianll** [comment]
It maybe a Jest issue or feature.

**Comment by armano2** [comment]
its actually works with class-components and property-decorators (alpha) but it fails with vfd

**Comment by ruojianll** [comment]
@armano2 Do you have any ideas of this?

**Comment by ruojianll** [comment]
https://github.com/facing-dev/vue-facing-decorator/issues/54#issuecomment-1500019388
