### ISSUE TITLE
[Feature] Ability to not use @Component decorator on class without additional options

### ISSUE THREAD

**Issue by proggmatic** [facing-dev/vue-facing-decorator#34]
It would be great if we don't need to decorate every component class without additional options by @Component decorator. For transforming is enough to be inherited from Vue. Is it possible?

@Component                // No need to do this
class SomeComponent extends Vue { }

**Comment by ruojianll** [comment]
I have no idea about this. `@Component` is not only a identifier but also a transformer. Think it as a function applies on classes.

**Comment by proggmatic** [comment]
Actually vue-property-decorator (10.0.0-rc.3) or maybe vue-class-component (8.0.0-rc.1) do this. You don't need to set @Options decorator if no additional config required. That's why i've proposed this feature.

**Comment by ruojianll** [comment]
https://www.npmjs.com/package/vue-class-component?activeTab=versions
There is not a rc.3 version. Could you provide a link to source code?

**Comment by ruojianll** [comment]
I find a way to implement, it's setting default `__vccOpts` on VFD class component root prototype. But I don't want to use `__vccOpts` if it's not necessary, because vue may remove it in future versions, they don't like class component. I don't want this repo relies on vue implementation details.
