### ISSUE TITLE
A warning is issued when a "update:modelValue" event emit.

### ISSUE THREAD

**Issue by jinyongp** [facing-dev/vue-facing-decorator#35]
Hi. There's a very annoying warning.

When the "update:modelValue" event occurs, the following warning is issued that cannot even be captured by `warnHandler`.

`
[Vue warn]: Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.
`

It is identical even if you use the Model Decorator as in the example.

Currently, the only way to resolve this is to add `emits: ['update:modelValue']` to the `Component` decorator.

Link to check for reproduction: https://stackblitz.com/edit/vitejs-vite-hz1wot?file=src/components/Counter.vue

```vue
<!-- App.vue -->
<template>
  <Counter v-model="count" />
  <span>Count: {{ count }}</span>
</template>

<script lang="ts">
import Counter from './components/Counter.vue';
import { defineComponent } from 'vue';

export default defineComponent({
  data() {
    return {
      count: 0,
    };
  },
  components: { Counter },
});
</script>
```

```vue
<!-- ./components/Counter.vue -->
<template>
  <div
    :class="$style.counter"
    @click="$emit('update:modelValue', modelValue + 1)"
  >
    Click Here
  </div>
  <!-- <div
    :class="$style.counter"
    @click="value += 1"
  >
    Click Here
  </div> -->
</template>

<script lang="ts">
import { Component, Prop, Model, Vue } from 'vue-facing-decorator';

@Component({
  // emits: ['update:modelValue'], // <-- This line is the only way to fix the problem.
})
class CounterComponent extends Vue {
  @Prop({ default: 0 })
  readonly modelValue!: number;

  // @Model({ default: 0 }) // <-- Make warning too
  // value!: number;
}

export default CounterComponent;
</script>

<style scoped module>
.counter {
  padding: 0.5rem 1rem;
  margin: 1rem;
  border-radius: 1rem;
  border: 1px solid white;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  user-select: none;
}
</style>

```

```js
// main.js
import { createApp } from 'vue';
import './style.css';
import App from './App.vue';

const app = createApp(App);

app.config.warnHandler = (msg, vm, trace) => {
  console.log("Warning's here!"); // <-- is not printed
  console.log(msg, vm, trace);
};

app.mount('#app');

```

Does this issue only happen to me? Strange that the issue has not yet been posted here.

**Comment by ruojianll** [comment]
`emits:[...]` is not set by `@Model`, So you should set it. It may be supported in the future version.

**Comment by jinyongp** [comment]
oh, ok. I've just seen [it](https://v3-migration.vuejs.org/breaking-changes/emits-option.html#migration-strategy). BTW, I want to ignore that warning. but it seem to be not captured by `app.config.warnHandler`. Is it not warning of vue?

**Comment by ruojianll** [comment]
It is seems from vue. I don't know why it can't be captured.

**Comment by armano2** [comment]
> `emits:[...]` is not set by `@Model`, So you should set it. It may be supported in the future version.

in my opinion `@Model` should not set emits options, as it limits users from defining validators for it

**Comment by ruojianll** [comment]
> > `emits:[...]` is not set by `@Model`, So you should set it. It may be supported in the future version.
> 
> in my opinion `@Model` should not set emits options, as it limits users from defining validators for it
> 
> https://vuejs.org/guide/components/events.html#declaring-emitted-events
> 
> missing emits can be easily handled eslint rule, @ruojianll if you are interested i could push some of eslint rules that i made so far :)

Thank you, but should eslint rules be included in user's project not v-f-d?
