### ISSUE TITLE
Use with TS and without a build-step (ES modules syntax)

### ISSUE THREAD

**Issue by johandanforth** [facing-dev/vue-facing-decorator#36]
For various reasons I'm using Vue, with typescript, but without a build-step. I'm using [ES modules syntax](https://vuejs.org/guide/quick-start.html#using-the-es-module-build). I'd prefer to use a class for Vue 3 and was hoping vue-facing-decorator could help me out. It doesn't seem that ES module syntax is supported, correct?

The kind of code I'm writing with Vue 3:

```
<div id="app">{{ message }}</div>

<script type="module">
  import { createApp } from 'https://unpkg.com/vue@3/dist/vue.esm-browser.js'

  createApp({
    data() {
      return {
        message: 'Hello Vue!'
      }
    }
  }).mount('#app')
</script>

```

So, does [vue-facing-decorator](https://facing-dev.github.io/vue-facing-decorator/) support ESM style coding?

**Comment by ruojianll** [comment]
v-f-d is a decorator library. It doesn't matter if you use es modules syntax or not. Does your build tool(webpack or vite) support load esm through url?

**Comment by ruojianll** [comment]
https://github.com/facing-dev/vue-facing-decorator/discussions/40
