### ISSUE TITLE
支持createDecorator自定义装饰器吗

### ISSUE THREAD

**Issue by hmxxmh** [facing-dev/vue-facing-decorator#38]
import { createDecorator } from "vue-class-component";
在vue-class-component可以引入createDecorator ，进行装饰器自定义，这个能支持吗，或者有没有类似其他方案

**Comment by ruojianll** [comment]
目前不支持

**Comment by ruojianll** [comment]
Implemented custom decorator in v2.1.20
https://facing-dev.github.io/vue-facing-decorator/#/en/custom/custom
