### ISSUE TITLE
怎么和element-plus的表单验证整合起来？

### ISSUE THREAD

**Issue by bruceauyeung** [facing-dev/vue-facing-decorator#39]
能给个示例吗？

**Comment by LCH7700** [comment]
首先你的el-form要设置ref，如下：
<img width="859" alt="image" src="https://user-images.githubusercontent.com/37178705/231833543-5dc638a9-7c23-4eda-bd2a-5648a0b4a34c.png">
然后使用@Ref()获取实例，注意，不能在@Ref()里设置别名，然后属性名要和上面表单设置的一致，如下：
<img width="613" alt="image" src="https://user-images.githubusercontent.com/37178705/231833661-69384e5e-f23f-4422-89ad-b906b0fd52d2.png">
最后在方法里按照下面使用，进行表单校验，前提是你的表单校验规则都已经写好了，如下：
<img width="893" alt="image" src="https://user-images.githubusercontent.com/37178705/231834063-bd4ea702-99e0-4899-aa4c-b0939acb11f2.png">
最后的最后，如果不用@Ref()的话，我最后一张截图里的两行注释也是可以用的，也能获取到表单的实例。希望对你有帮助。
