### ISSUE TITLE
Option to import template from separate html file?

### ISSUE THREAD

**Issue by Pazulay** [facing-dev/vue-facing-decorator#4]
Is there an option to create a component.ts and template.html and use the template in the component?

Example:

@Component({
  template: require('./example-component.component.html')
})
export default class ExampleComponent extends Base {}

**Comment by ruojianll** [comment]
That will be released in 1.0.7

the feature needs a vue full build. https://vuejs.org/api/options-rendering.html#template

**Comment by Pazulay** [comment]
Can you include an example of this in the Documents website? I can't get it to work.
Thanks

**Comment by ruojianll** [comment]
```
import {Component,Vue} from 'vue-facing-decorator'
@Component({
  template:'<div>your template string</div>'
})
class Comp extends Vue{

}
```

`template` option needs vue compiler bundle.

https://facing-dev.github.io/vue-facing-decorator/#/class-component/component/component?id=template

**Comment by Pazulay** [comment]
I know. That works for me. I'm talking about importing the html from an external html file into the template.

Example:

component.html:
`
<div>Your template goes here</div>
`

component.ts
`
import {Component,Vue} from 'vue-facing-decorator'
import html from './component.html'

@Component({
  template: html;
})
class Comp extends Vue{

}
`

**Comment by ruojianll** [comment]
Let webpack do this.

https://webpack.js.org/guides/asset-modules/

**Comment by shanda-hemiao** [comment]
> Let webpack do this.
> 
> https://webpack.js.org/guides/asset-modules/

Is there a loader that is already available to solve this problem? For example, the previous vue-template-loader.
I used it this way when I was at 2. x.

>  webpack rules config
``` javascript
_config = {
     module: {
               rules: [
                    // ...... other rules
                    {
                        test: /\.html$/,
                        loader: 'vue-template-loader',
                        include: /src/
                    }
                ]
            },
       // ...... other config
}
```

> typing definition in template.d.ts
``` typescript
declare module '*.html' {
    import Vue from 'vue';
    interface WithRender {
        <V extends Vue>(options: Vue.ComponentOptions<V>): Vue.ComponentOptions<V>;
        <V extends typeof Vue>(component: V): V;
    }
    const withRender: WithRender;
    export = withRender;
}
```

> component usage
``` typescript
import Template from './Login.html';
@Template
@Component({
    components: {}
})
export default class Login extends Vue{
      //....other code
}
```

**Comment by ruojianll** [comment]
You could try this pattern:
```
//myComp.vue
<template>
<div>Your template</div>
</template>
<script lang="ts">
import MyComp from './myComp'

export default MyComp
</script>

//myComp.ts
import {Component,Vue} from 'vue-facing-decorator'
@Component
export default MyComp extends Vue{
//...
}

```

Separate your typescript part to another file.
