### ISSUE TITLE
Inheriting multiple classes

### ISSUE THREAD

**Issue by rootux** [facing-dev/vue-facing-decorator#5]
Hey.

Can you add in your documentation how to perform the following.

I have this class for example
 
```
export default MyClass extends QBtn {
...
}
```

I would like to inherit from Base.
What shall I do?

QBtn is an external library ([Quasar](https://quasar.dev/vue-components/button))

**Comment by ruojianll** [comment]
It will be support by `mixins` vue option api in 1.0.7. `extends` api is use by this package internally to extends @ComponentBase component, so I won't to expose it. The strategy of `mixins` and `extends` is according to vue implementation.

**Comment by ruojianll** [comment]
v1.0.7 release.

**Comment by ruojianll** [comment]
Readme is also updated

**Comment by rdhelms** [comment]
@rootux Do you happen to have an example app using both quasar and vue-facing-decorator? We’ve had someone else ask about that, but I’m not very familiar with quasar

**Comment by rootux** [comment]
It was an old project for a client which unfortunately I can’t disclose.
