### ISSUE TITLE
[Feature Request] support aync computed property

### ISSUE THREAD

**Issue by bruceauyeung** [facing-dev/vue-facing-decorator#50]
just like https://github.com/foxbenjaminfox/vue-async-computed + https://github.com/foxbenjaminfox/vue-async-computed-decorator

**Comment by bruceauyeung** [comment]
@ruojianll any plans ?

**Comment by ruojianll** [comment]
I'm working on an another PR now. After that, I will consider this feature. Thank you for this valuable issue.

**Comment by ruojianll** [comment]
It seems not the work v-f-d should do. If someone implement it in vue 3. I'd like to wrap it as a decorator.
