### ISSUE TITLE
VFD Incompatible With Jest

### ISSUE THREAD

**Issue by cah-keyan-hardman** [facing-dev/vue-facing-decorator#54]
First off - thank you so much for this library, it's much appreciated. However, in an effort to update many projects from Vue2 to Vue3 it would be extremely helpful if I could continue using jest. I receive the following error:

```
Test suite failed to run

    TypeError: Class constructors cannot be invoked without 'new'

      13 |
      14 | @Component({ components: { Sidebar } })
    > 15 | export default class App extends Vue {
         | ^
      16 |   @Prop({ required: false }) private userContext?: UserContext
      17 |
      18 |   loaded = false
```

Please let me know what other info I can provide to address this. This was brought up before but the issue was closed:
https://github.com/facing-dev/vue-facing-decorator/issues/33

**Comment by ruojianll** [comment]
Which version of v-f-d you are using?

**Comment by cah-keyan-hardman** [comment]
Thank you for the respond ruiojianll - I am using 
`"vue-facing-decorator": "^2.1.15",`

**Comment by ruojianll** [comment]
Would you share you project for testing?

**Comment by ruojianll** [comment]
Found it. It's a vue-jest issue.
https://github.com/vuejs/vue-jest/blob/master/packages/vue3-jest/lib/utils.js#L116
vue-jest force applies ts target to es5, it causes the native v-f-d base class is not compatible with transformed component class in .vue file. ES6 is vue3 basic environment, so I won't change v-f-d for ES5.
vue-jest for vue3 should upgrade to ES6.

**Comment by cah-keyan-hardman** [comment]
Thanks for the info!

**Comment by ruojianll** [comment]
As I mentioned, that's a vue-jest issue. You could try Vitest. https://github.com/facing-dev/vue-facing-decorator/issues/33#issuecomment-1410648544
