### ISSUE TITLE
当时使用@Ref()获取组件实例时，组件的方法不能被感知到调用，也无法进行跳转

### ISSUE THREAD

**Issue by LCH7700** [facing-dev/vue-facing-decorator#56]
我的环境：
"vue": "^3.2.47",
"vue-facing-decorator": "^2.1.20",
"typescript": "^4.9.5",
开发工具：WebStorm 2023.1

问题1：正如我标题所说的那样。
![image](https://user-images.githubusercontent.com/37178705/231452766-8a6e2cf7-c81c-4500-ba1f-fb36c2711c71.png)
问题2：钩子函数被被当成了普通方法一样，不能高亮显示。
![image](https://user-images.githubusercontent.com/37178705/231453005-6451b2f0-415e-4d97-a2dc-dc3d4b54c9ed.png)

**Comment by LCH7700** [comment]
抱歉，刚发出这个issues我就发现了我的错误，没想到回复的如此之快，我想关闭都来不及了😄

**Comment by ruojianll** [comment]
@LCH7700 客气了，欢迎多给宣传宣传
