### ISSUE TITLE
使用@Emit()进行通知父组件所携带的数据为undefined

### ISSUE THREAD

**Issue by LCH7700** [facing-dev/vue-facing-decorator#57]
如下图我在子组件定义了onSubmit方法，有一个参数，在submit方法调用并入参，通知父组件在submitAudit方法里收到通知，但是所拿到的data是undefined，如下两张图所示：
过程：
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/37178705/231932295-e599cc9e-5f7d-4628-9ab6-70cdf0beac70.png">
结果：
<img width="627" alt="image" src="https://user-images.githubusercontent.com/37178705/231932622-7539301f-12d1-4dbb-a10a-c7728d5d0ad3.png">
使用原生的this.$emit()是正常的，我看文档并没有比较全面的例子；而且在我也尝试了在@Component里设置了emits:[]，但是这个只有使用原生的this.$emit()才有用，是我使用过程有什么错误么？还是这是一个bug？

**Comment by ruojianll** [comment]
![image](https://user-images.githubusercontent.com/15936492/231956740-8c54ab7a-d7f0-4021-aae9-304f9d190a73.png)

**Comment by LCH7700** [comment]
> ![image](https://user-images.githubusercontent.com/15936492/231956740-8c54ab7a-d7f0-4021-aae9-304f9d190a73.png)

原来如此！感谢！我看错了文档，看到了类组件->组件->选项->emit
