### ISSUE TITLE
VModel Usage/Explanation (some features missing?)

### ISSUE THREAD

**Issue by DeRiderConsultingServices** [facing-dev/vue-facing-decorator#58]
A past user of @vue-property/class decorator and have been holding off migrating to Vue3 due to the lack of a compatible project so this is a really cool project/endeavor. Great work!

While trying to migrate some code I noticed that @PropSync is missing and after some poking around I saw there was a @VModel decorator which, with a bit of trial and error, I sort of got working with two minor caveats.
Using as such in a child component
`	@VModel({ name: "selectedNumber" })
		secretSelectedNumber		: number;
`
and binding as such 
`<TestPropSyncAlternativesView v-model:selected-number="MySelectedNumber" />`

Gives me two-way databinding between a custom property and the parent. 
However every time the value changes/is bound  the following warning is emitted.

`[Vue warn]: Component emitted event "update:selectedNumber" but it is neither declared in the emits option nor as an "onUpdate:selectedNumber" prop.`

Additionally, there is no intellisense/navigation support for the `v-model:selected-number`  portion

So curious if I am missing something or any responses/etc somebody might have.

Thanks,

**Comment by rdhelms** [comment]
@DeRiderConsultingServices we ran into that warning in quite a few places, too, since Vue 3 now logs that warning whenever an emitted event is not registered in the component's `emits` property. So you should be able to get rid of the warning by adding the emits property like in this example:
https://v3-migration.vuejs.org/breaking-changes/v-model.html#migration-strategy

Instead of `VModel` (or `Model`...which I think is the newer name?) we opted to register the v-modeled modelValue prop using the normal `@Prop` decorator and then also use the `@Emit` decorator for the `update:modelValue` event, since that also registers the event name in the emits array.

@ruojianll I wonder if it would make sense for the `@Model` decorator to automatically register the modelValue event name (or custom event name) in `emits`, the same way that `@Emit` does?

**Comment by DeRiderConsultingServices** [comment]
Thanks for the response @rdhelms 



> @ruojianll I wonder if it would make sense for the `@Model` decorator to automatically register the modelValue event name (or custom event name) in `emits`, the same way that `@Emit` does?

i like that idea! My goal is to try to reduce as much ceremony as possible.

I'm curious @rdhelms  if you have to hear your experience with the intellisense for v-model:property-name. Do you get intellisense for this and if so what tooling do you use?

Thanks,

**Comment by rdhelms** [comment]
@DeRiderConsultingServices What type of intellisense/navigation behavior are you looking for with `v-model:customModelValue`? We don't actually use custom modelValue names, but we use the VS Code Volar extension and it seems like it shows the `customModelValue`'s type as `string` and it shows the value's type correctly. And Go To Definition on the modeled value works correctly.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/7010586/233754374-d1f49a97-28fd-442a-83cd-f77779dcb196.png">

<img width="510" alt="image" src="https://user-images.githubusercontent.com/7010586/233754783-eb654988-58cb-4ee5-ae21-9a4eeccc6fe6.png">

**Comment by DeRiderConsultingServices** [comment]
> @DeRiderConsultingServices What type of intellisense/navigation behavior are you looking for with `v-model:customModelValue`? We don't actually use custom modelValue names, but we use the VS Code Volar extension and it seems like it shows the `customModelValue`'s type as `string` and it shows the value's type correctly. And Go To Definition on the modeled value works correctly.
> 
> <img alt="image" width="412" src="https://user-images.githubusercontent.com/7010586/233754374-d1f49a97-28fd-442a-83cd-f77779dcb196.png">
> 
> <img alt="image" width="510" src="https://user-images.githubusercontent.com/7010586/233754783-eb654988-58cb-4ee5-ae21-9a4eeccc6fe6.png">

Do you get completion for the cutomModelValue property name? I'm using WebStorm and I get nothing for the completion list so I have no idea if I'm typing it correctly or if it exists or if it doesn't exist. 

![image](https://user-images.githubusercontent.com/23038492/233755887-e3059de2-6f9a-4959-8338-0569afa28c28.png)

And don't know what reasonable expectations should be

**Comment by DeRiderConsultingServices** [comment]
Hmm I guess Volar half knows about it. No completion for it but once it's typed it actually finds it. 

![image](https://user-images.githubusercontent.com/23038492/233756400-fdb2d552-732a-4ff0-90bd-35feb37ebd9d.png)

**Comment by ruojianll** [comment]
VModel doesn't set emits in the current version. You could set it in `@Component({emits:['update:modelValue','update:xxx']})` manually. VModel will set it in next version.
