### ISSUE TITLE
Use within Vue SFCs?

### ISSUE THREAD

**Issue by corwin-of-amber** [facing-dev/vue-facing-decorator#62]
Since vue-facing-decorator is an adapter to an options object, I was expecting to be able to use it in the `<script>` section of a single-file component.
```html
<template><div>some html</div></template>
<script>
import { Component, Vue } from 'vue-facing-decorator'

@Component
export default class A extends Vue { }
</script>
```

But it seems that the template part gets overridden. Is there an example for a `.vue` file that uses vue-facing-decorator?

**Comment by rdhelms** [comment]
Hi @corwin-of-amber 👋 

vue-facing-decorator's class components need to be used within `<script lang="ts">` blocks:
https://facing-dev.github.io/vue-facing-decorator/#/en/quick-start/quick-start?id=in-vue-single-file-components

Hopefully that helps!

**Comment by corwin-of-amber** [comment]
Thanks for the pointer -- I in fact did just that (my original code *was* in TypeScript), and it did not work but I will specifically try using that link, not clear how I could have missed it, and report back.

**Comment by corwin-of-amber** [comment]
Looks like there is some mishap with my bundler config, so the problem is definitely not in vue-facing-decorator.
Thanks again for your help!
