### ISSUE TITLE
Global methods are undefined when used in class fields

### ISSUE THREAD

**Issue by iv-thomson** [facing-dev/vue-facing-decorator#63]
When global method is used inside a class body it triggers an error.

### How to reproduce:
main.ts
```
app.config.globalProperties.$test = () => "hello I'm func"
```

App.vue - TypeError: this.$test is not a function
```
<script lang="ts">
@Component({})
export default class App extends Vue {
  public msg = this.$test();
}
</script>
```
App.vue - this works just fine
```
<script lang="ts">
export default {
  data() {
    return {
      msg: this.$test(),
    }
  }
}
</script>
```
Try reproducing it yourself in this repo: https://github.com/iv-thomson/vue-facing-decorator-global-methods-issue

### Workaround is to use 
```
import { Vue } from 'vue-facing-decorator';
Vue.prototype.$test = () => "hello I'm func"
```

#### I'd like to know if this behavior is expected  or not. Maybe it makes sense to augment Vue base class prototype on the library's side?

I also faced the same exact issue with `this` context binding. Unfortunately it is not clear for me if there's a workaround for that other then using `bind` when in used in the class field.

**Comment by ruojianll** [comment]
`this` context is not available when initial a class field now. You could try to call it in `onMounted` by `this.msg = this.$test()`. I will try to support it in the future. Keep this issue open.

**Comment by ruojianll** [comment]
Initialing a class field with this context will be remove in the next version.
