### ISSUE TITLE
Cannot combine @Watch with @Emit

### ISSUE THREAD

**Issue by scscgit** [facing-dev/vue-facing-decorator#66]
Repro: https://stackblitz.com/edit/vitejs-vite-t3ipir?file=src%2Fcomponents%2FCounter.vue

In [vue-class-component](https://github.com/vuejs/vue-class-component) + [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator), I was able to use a following combination of decorators:

```ts
@Emit()
@Watch('value', { immediate: true })
watchValue(value) {
  return value;
}
```

It caused the emit **both** initially (due to `immediate`) **and** after each change of the watched variable. In _vue-facing-decorator_, the `@Watch` doesn't trigger the `@Emit`.

**Comment by rdhelms** [comment]
@scscgit Just a note that your stackblitz repro is erroring for me, but I added a `tsconfig.json` file with 
```ts
{
  "compilerOptions": {
    "experimentalDecorators": true
  }
}
```
and then it worked. The issue you're describing is definitely evident in that repro by clicking the "Increment" div and seeing that the count doesn't increment (unless the "Emit" div is also clicked)

**Comment by ruojianll** [comment]
@alecgibson Would you like to resolve some issues?

**Comment by ruojianll** [comment]
It doesn't support to combine decorators on one field at the moment.
