### ISSUE TITLE
Usage with vuex-class library

### ISSUE THREAD

**Issue by armenohanyan15** [facing-dev/vue-facing-decorator#68]
We are trying to migrate from the vue-property-decorator/vue-class-component to the vue-facing-decorator but facing issues while using it with vuex-class library.  Particularly Getters and Actions from vuex-class are undefined in the class component 

```
import { Component, Vue } from 'vue-facing-decorator'
import {Getter} from 'vuex-class'
@Component
export default class MyComponent extends Vue {

	@Getter('getData') readonly data!: IData[]
}
```

In this case the Getter is not working, its showing undefined. Is there an compatibility issues between this repo and vuex-class decorators?

**Comment by norayr15** [comment]
I have the same problem too
I can't find a solution

**Comment by rdhelms** [comment]
@armenohanyan15 Are you using vite or webpack? Also, what versions of vue, vuex-class, and vue-facing-decorator are you using?

**Comment by rdhelms** [comment]
Also @norayr15 same question as above 😄

**Comment by norayr15** [comment]
@rdhelms 
I am using the vue3 version

**Comment by rdhainaut** [comment]
@norayr15 @armenohanyan15 you should share your package.json to show what versions you are using in your project

**Comment by davidoff0895** [comment]
same issue. I'm using webpack with these dependency versions
<img width="267" alt="image" src="https://github.com/facing-dev/vue-facing-decorator/assets/29586170/aeb48eb5-ba1f-48ae-abdc-7bd477dad7b3">

**Comment by ruojianll** [comment]
try https://github.com/wangzhiguoengineer/vuex-facing-decorator
