### ISSUE TITLE
TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by Flippeey** [facing-dev/vue-facing-decorator#7]
Hi, thank you for setting up this project. I've been waiting for a while for someone to continue with the vue-class-component package.
I was trying today to migrate my project away from vue-class-component and vue-property-decorator to your library, but unfortunately ran into some issues. 

One of the errors I'm trying to solve now is: 
![image](https://user-images.githubusercontent.com/5073998/174314908-9aae4138-9151-40bc-a9a3-e44edfae3483.png)

The issue seems to come from the new BaseComponent that I made to replace the Mixins that I had before. I followed the documentation to set it up this way.

```	
BaseComponent.vue
       @ComponentBase
        export default class BaseComponent extends Vue { }

MyComponent.vue
	@Component({ components: BaseComponent })
	export default class MyComponent extends BaseComponent { }
```
I tried to add it in the components  property of my component to make sure it is imported, so that is not the issue I think. I'm not sure what I am doing wrong. Any suggestions?

**Comment by ruojianll** [comment]
Which version is this?

**Comment by Flippeey** [comment]
> Which version is this?

2.0.4

**Comment by ruojianll** [comment]
BaseComponent(decorated by ComponentBase) is just use for extending. You shouldn't use it in `{components:{}}`.

Use ComponentBase for extending or Component for vue instance.

**Comment by Flippeey** [comment]
Okay I removed the import for BaseComponent, but the issue remains.
Did you mean I also have to split up my BaseComponent?
![image](https://user-images.githubusercontent.com/5073998/174324089-0ae7314f-3a84-4ac3-a4c5-953e3dc7933d.png)

Do I need to make a separate class that extends Vue and then use ComponentBase to extend that class?

**Comment by ruojianll** [comment]
The default exported component should be Component, not ComponentBase.

Use
```
@Component
export default Comp extends Vue{
}
```

or extending version
```
@ComponentBase 
class CompBase extends Vue{
}

@Component
export default class Comp extends CompBase{
}
```

**Comment by ruojianll** [comment]
> Okay I removed the import for BaseComponent, but the issue remains. Did you mean I also have to split up my BaseComponent? ![image](https://user-images.githubusercontent.com/5073998/174324089-0ae7314f-3a84-4ac3-a4c5-953e3dc7933d.png)
> 
> Do I need to make a separate class that extends Vue and then use ComponentBase to extend that class?

No.
`Component` generates standard vue components, it could be used in vue template, option api components `{components:{Foo:Bar}}` where accepted standard vue components.
`ComponentBase` is a base class identifier used by this repo, so vue couldn't analyze use instance it.

**Comment by Flippeey** [comment]
I've found the issue finally after lots of searching. There were a few components that were being loaded somewhere in the component tree, that did not have @Component decorator yet. In the vue-class-component package it was not necessary to have this decorator everywhere. After going through all the components to make sure they have the decorator it seems to be working. Thanks for the help with explaining
