### ISSUE TITLE
使用 @vitejs/plugin-vue-jsx 会报错

### ISSUE THREAD

**Issue by w3cways** [facing-dev/vue-facing-decorator#70]
`import vue from '@vitejs/plugin-vue'
import vueJsx from '@vitejs/plugin-vue-jsx'

plugins: [
            vue(),
            vueJsx({
                babelPlugins: [
                    ['@babel/plugin-proposal-decorators', { legacy: true }],//不加这个会报错
                ],
            }),
        ]
`

tsx文件中，使用@Component 没有问题，加了  @Prop 就报错
`
import { Component, Prop, Vue, Emit, Watch } from 'vue-facing-decorator'
@Component({})
export default class Login extends Vue {
    @Prop() test!: Boolean //加上这个会报错

 render() {
        return (
            <div class="login" >
                test
            </div>
        )
    }
}

`

报错内容如下
[plugin:vite:vue-jsx] unknown file: Definitely assigned fields cannot be initialized here, but only in the constructor

**Comment by ruojianll** [comment]
还是写到ts文件里吧

**Comment by pecasha** [comment]
请问这个问题有解决了吗

**Comment by TechQuery** [comment]
> 还是写到ts文件里吧，然后import

@ruojianll 不是函数组件的话，TSX 渲染函数文件分开太麻烦了……

> 请问这个问题有解决了吗

@pecasha 用 Parcel 完全没这个问题，配置还非常简单，按 Babel、TSC 官方配置即可，剩下的都自动处理，我已经成功跑起来了：https://github.com/idea2app/Vue-MobX-Prime-ts/pull/10
