### ISSUE TITLE
如何实现 Provide 响应式数据提供

### ISSUE THREAD

**Issue by OSpoon** [facing-dev/vue-facing-decorator#80]
@Provide 所装饰的类属性，在发生改变后并没有引起子组件中对应注入数据的变化，目前不知道如何实现 Provide 的响应式数据提供。

@Provide 与 @Component 中 provide 选项的区别是什么？我以为是响应式数据和常量数据的区别。

-- 我是这几天刚学习这个框架。

**Comment by ruojianll** [comment]
@alecgibson He asked that why a provided field is not reactive in the children injections when it changed.

**Comment by alecgibson** [comment]
Can we get a failing test case? Have they made sure to follow the upstream [Vue docs](https://vuejs.org/guide/components/provide-inject.html#working-with-reactivity):

> In order to make injections reactively linked to the provider, we need to provide a computed property using the [computed()](https://vuejs.org/api/reactivity-core#computed) function

**Comment by alecgibson** [comment]
I opened a draft PR: https://github.com/facing-dev/vue-facing-decorator/pull/81

I'm not super happy with it.

In the meantime, you can work around this by using `@Component({})`:

```ts
@Component({
  provide() {
    return {
      providedValue: computed(() => this.dataValue)
    }
  }
})
```

**Comment by alecgibson** [comment]
See [the docs](https://vuejs.org/guide/components/provide-inject.html#working-with-reactivity):

> The above usage requires setting `app.config.unwrapInjectedRef = true` to make injections automatically unwrap computed refs. This will become the default behavior in Vue 3.3 and this config is introduced temporarily to avoid breakage. It will no longer be required after 3.3.
