### ISSUE TITLE
Few problems with custom decoratos

### ISSUE THREAD

**Issue by SasePriv** [facing-dev/vue-facing-decorator#84]
We are in the proccess of migrating vue 2 to vue 3 and we few problems with the custom decorators:

- First we have a lot of componentes with this structure:
![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/4dbba1b5-0251-41b5-8cd9-8d78009bfbd2)
Whit vue 2 we was using vue-class-component and vue-property-decorator, and this was working perfectly, but now we migrate to vue-facing-decorator, that customer decorator not work anymore, I have checked and they do not run .

- Second i searching a solution and i moved that decorators to inside of the class component to check if work or not and works halfway:
![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/5b0ce413-f685-40ef-9745-cbc1ed0dccee)
The decorator `@Name` work perfectly but the others three only work the first of the three, like you see in the image, if i put frist the decorator @MapGetters work perfectly and the others two not, but if i move the `@MapActions` above the `@MapGetters` only the `@MapActions` will work and the other not.

This si the the code of the custom decorators:

```
import { createDecorator } from 'vue-facing-decorator';

import { mapActions, mapGetters } from 'vuex';

export function MapGetters(getterNames) {
  return createDecorator((options) => {
    if (!options.computed) options.computed = {};
    Object.assign(options.computed, mapGetters(getterNames));
    console.log('options', getterNames);
  });
}

export function MapActions(actionNames) {
  return createDecorator((options) => {
    if (!options.methods) options.methods = {};
    Object.assign(options.methods, mapActions(actionNames));
  });
}

export function Components(componentNames) {
  return createDecorator((options) => {
    if (!options.components) options.components = {};
    Object.assign(options.components, componentNames);
  });
}

export function Mixins(mixinNames) {
  return createDecorator((options) => {
    if (!options.mixins) options.mixins = [];
    options.mixins.push(...mixinNames);
  });
}

export function Name(target, key) {
  createDecorator((componentOptions, k) => {
    componentOptions.name = k;
  })(target, key);
}
```

**Comment by kdlslyv** [comment]
to me it looks unrelated regarding vue-facing-decorator

My guess is that for vue3 use you should look into changing the pattern for that [vuex usage](https://stackoverflow.com/questions/63216740/use-mapactions-or-mapgetters-with-vuex-4-and-vue-3)

**Comment by SasePriv** [comment]
i also change the custom hook to use `useStore` and throw me a error that is undefined

**Comment by kdlslyv** [comment]
https://github.com/wangzhiguoengineer/vuex-facing-decorator

from another issue here in this repo, I suppose that works.
I've settled with Pinia via https://github.com/PentaTea/pinia-class-component/tree/main in vue3.

**Comment by SasePriv** [comment]
I have seen that library but the application I have is very large so changing all the decorators in all the components would be very tedious.

**Comment by ruojianll** [comment]
@SasePriv  Why doesn't your `@Name` return the function, but call it directly?

**Comment by ruojianll** [comment]
@SasePriv You could check options in every decorators and check it by `console.log(toNative(Dashboard))` finally. If the component generated correctly, this is not a v-f-d issue.

**Comment by SasePriv** [comment]
This the output of the console log:

![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/501072c0-4297-467c-a1bf-17cc3be2ecf9)

**Comment by ruojianll** [comment]
@SasePriv try v3.0.2

**Comment by SasePriv** [comment]
Still not working, i commented the others custom decorators and only leave the @MapGetters decorato also does not work:
![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/31d72521-29bd-437b-9fa3-e25d28275c96)

The custom decorator still the same:
![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/91fb4081-88a0-4183-b2e8-fcd8c74f0624)
In the console i only see the frist one but second one never show:
![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/0dd99fbb-c005-4821-a5ec-6fe044b038e4)

This is other `console.log(toNative(Dashboard))`:
![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/67d0f16b-a16d-4e75-be4c-64ce33bd5e30)

**Comment by ruojianll** [comment]
Class decorator cannot be supports now, only field decorators.

**Comment by SasePriv** [comment]
I understand, it would be nice if somewhere in the documentation you could put that you can't use the class decorators yet.

Another thing, with the new version I released that allowed multiple custom decorators in a field, I have taken the following approach to solve my problem:

![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/b80973fb-abcb-466e-8739-6f21ce399157)

I moved the decorators inside the class, and I put it in a variable, this way I simulate the class decorators since the options that I get in the custom decorator is the dashboard one:

![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/5d9f793a-c09e-442c-8fe5-e748342fad13)

![image](https://github.com/facing-dev/vue-facing-decorator/assets/47802417/9e4b7728-f6c1-4df6-b8e6-94a3713cfef3)

So i think this can be a solution for that people who want to use class decorators
