### ISSUE TITLE
Vue Router hooks

### ISSUE THREAD

**Issue by NikitaPoplavskiy** [facing-dev/vue-facing-decorator#85]
Hi there,

How i can use beforeRouteUpdate and beforeRouteLeave hooks using vue-facing-decorator?

**Comment by ruojianll** [comment]
try `@Hook`

**Comment by ruojianll** [comment]
https://facing-dev.github.io/vue-facing-decorator/#/en/class-component/hooks/hooks?id=for-other-names

**Comment by NikitaPoplavskiy** [comment]
i've tried something like that:
import { ComponentBase, Ref, Watch, Hook, Vue } from 'vue-facing-decorator'
@ComponentBase({})
export default class OneEventPageComponent extends Vue {
    @Hook
    beforeRouteLeave(to: any, from: any, next: any) {
      console.log(to)
    }
  }
  
  and beforeRouteLeave isn't been handled when i tried to leave from route.

**Comment by ruojianll** [comment]
Log the result of `toNative(OneEventPageComponent)` please.

**Comment by matteoscaramuzza** [comment]
I have experienced this issue.
It may be because the component is not the main component specified in the router definition.

If you move your @Hook declaration it should work.

**Comment by rdhelms** [comment]
@NikitaPoplavskiy Just wanted to mention another possible solution here. Have you been able to resolve this for your context?

```ts
@Component({
    options: {
        beforeRouteUpdate (this: ExampleComponent, to, from, next) {
            // do stuff
        }
    }
})
export default class ExampleComponent extends Vue {}
```
