### ISSUE TITLE
[Feature] - Allow to extend ComponentConsOption type definition.

### ISSUE THREAD

**Issue by juanparati** [facing-dev/vue-facing-decorator#88]
I am using vue-facing-decorator with [InertiaJS](https://inertiajs.com/), InertiaJS implement some custom Component options like "[layout](https://inertiajs.com/pages#persistent-layouts)" that I use in order to render persistent layouts. Those layouts works great with my component using vue-facing-decorator, however the property definition is not recognized by typescript and I have to use "ts-ignore" in order to ignore the type errors.

Is it any way of extend the ComponentConsOption in order to accept custom properties?

I provide and example of a component that use the layout:

```
import {Vue, Component} from 'vue-facing-decorator';
import DefaultLayout from "@/Layouts/DefaultLayout.vue";

@Component({
    // @ts-ignore
    layout: DefaultLayout
})
export default class UserList extends Vue {
}
```

**Comment by ruojianll** [comment]
Try this https://facing-dev.github.io/vue-facing-decorator/#/en/class-component/component/component?id=options-1 for a temporary resolution.
