### ISSUE TITLE
computed conflicts with the get property in the class

### ISSUE THREAD

**Issue by alamhubb** [facing-dev/vue-facing-decorator#94]
![3760eeb742a5c42561600c1a7f479306](https://github.com/facing-dev/vue-facing-decorator/assets/14007972/16fd97e1-fb9f-40a0-b0e7-1edfe43955de)

![cdd38104af3802bd153eda7bf33141c1](https://github.com/facing-dev/vue-facing-decorator/assets/14007972/54b55c73-32d4-4c51-bd33-3a871a02aa7a)

 我用了computed，get就失效了

**Comment by TonyLin0201** [comment]
any update on it?

**Comment by ruojianll** [comment]
In class component, get is vue's computed property. If you want es class native get, use `@Vanilla`.
