### ISSUE TITLE
@Model not work

### ISSUE THREAD

**Issue by alamhubb** [facing-dev/vue-facing-decorator#97]
我这样写的代码，但是没有效果
```
@Model files!: DomFile[] 
```

![image](https://github.com/facing-dev/vue-facing-decorator/assets/14007972/bd0a86b4-23e4-42d5-b409-216fa164ce93)

![image](https://github.com/facing-dev/vue-facing-decorator/assets/14007972/8b8cd356-2e4e-4103-ae81-6e579b28d4a7)

need add code  can work

```
  @Emit('update:modelValue')
  change() {
    const files = this.fileList.map(item => item.files).flat()
    console.log(files)
    return files
  }
```

**Comment by ruojianll** [comment]
I tested it, `@Emit('update:modelValue')` works well with `@Model`.
