### ISSUE TITLE
npm仓库的版本是3.0.4，而release和tag版本是3.0.3，请更新一下release和tag版本到3.0.4

### ISSUE THREAD

**Issue by wangzhiguoengineer** [facing-dev/vue-facing-decorator#99]
npm仓库最新版本是3.0.4
![image](https://github.com/facing-dev/vue-facing-decorator/assets/16033868/f22bac47-fc5a-41a6-9b7b-d5b96130f746)

GitHub的release和tag版本是3.0.3
![image](https://github.com/facing-dev/vue-facing-decorator/assets/16033868/df1726db-fd18-4466-b02b-629b9e60ffe8)

npm仓库的版本是3.0.4，而release和tag版本是3.0.3，请更新一下release和tag版本到3.0.4

**Comment by ruojianll** [comment]
released
